name: SFTP Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install  SSH Client
        run: sudo apt-get install -y openssh-client

      - name:  Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SFTP_PRIVATE_KEY }}" > ~/.ssh/galmalka
          chmod 600 ~/.ssh/galmalka
          ssh-keyscan -H ${{ secrets.SFTP_HOST }} >> ~/.ssh/known_hosts
          echo "${{ secrets.SFTP_PRIVATE_KEY }}"

      - name: Transfer Files via SFTP
        run: |
          sftp -i ~/.ssh/galmalka -oPort=${{ secrets.SFTP_PORT }} ${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_HOST }} << EOF
          put -r index.js ./index.js
          EOF